# Generated by Django 4.0.5 on 2022-06-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_details_balance1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='address',
            new_name='receiver_address',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='private_key',
            new_name='sender_address',
        ),
        migrations.AddField(
            model_name='details',
            name='sender_private_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
